"""
Pydantic DTO (Data Transfer Object) schemas for Project entity.

What is a DTO:
    A DTO is a plain data container that defines the shape of data
    crossing a boundary — in this case, the HTTP API boundary.

    The ORM model (app.models.project.Project) is the database representation.
    The DTO schemas are the API representation.
    They are intentionally separate — the API contract should not be
    coupled to the database schema.

Why separate Create/Update/Response schemas:
    Security — prevents over-posting attacks.
    Clarity — each endpoint has an explicit contract.
    Flexibility — you can change the API without changing the DB schema.
"""

from uuid import UUID
from datetime import datetime
from pydantic import BaseModel, Field, field_validator, model_validator
from typing import Self

from app.models.project import ProjectStatus


# ══════════════════════════════════════════════════════════════════════════════
# Request DTOs — what the client sends TO the server
# ══════════════════════════════════════════════════════════════════════════════

class ProjectCreate(BaseModel):
    """
    DTO for POST /projects — creating a new project.

    Why this schema exists:
        The client should ONLY be able to set name, owner, and status.
        The client must NEVER be able to set:
            - id (generated by the database)
            - created_at (set by the database)
            - updated_at (set by the database)

        Without this schema, a malicious client could send:
            POST /projects
            {
                "id": "00000000-0000-0000-0000-000000000001",
                "name": "Hacked Project",
                "created_at": "2000-01-01T00:00:00Z"
            }
        and potentially override database-generated values.
        This is called an "over-posting attack".

        With this schema, Pydantic rejects any extra fields automatically.

    Validation rules:
        - name: 1-255 characters, leading/trailing whitespace stripped
        - owner: 1-255 characters, leading/trailing whitespace stripped
        - status: must be one of ProjectStatus enum values, defaults to "active"
    """

    name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Project name",
        examples=["Backend Platform", "Mobile App Redesign"],
    )

    owner: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Project owner (email or username)",
        examples=["alice@example.com", "bob.smith"],
    )

    status: ProjectStatus = Field(
        default=ProjectStatus.active,
        description="Project lifecycle status",
    )

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("name", "owner", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str) -> str:
        """
        Strips leading and trailing whitespace from string fields.

        Why this matters:
            "  Backend Platform  " and "Backend Platform" should be
            treated as the same name. Without stripping, you could
            create duplicate projects that differ only by whitespace.

        mode="before":
            Runs before Pydantic's built-in validation.
            This means we strip whitespace BEFORE checking min_length.
            "   " (3 spaces) becomes "" (empty string) and fails min_length=1.
        """
        return v.strip()

    @field_validator("name")
    @classmethod
    def validate_name_content(cls, v: str) -> str:
        """
        Additional validation beyond length — checks for invalid characters.

        Why this matters:
            Project names are displayed in URLs, logs, and file paths.
            Certain characters cause problems:
                - Null bytes (\x00) break C-based systems
                - Newlines (\n) break log parsers
                - Control characters are invisible and confusing

        This validator rejects names containing these characters.
        """
        if "\x00" in v:
            raise ValueError("Project name cannot contain null bytes")
        if "\n" in v or "\r" in v:
            raise ValueError("Project name cannot contain newlines")
        if any(ord(c) < 32 for c in v):
            raise ValueError("Project name cannot contain control characters")
        return v

    @model_validator(mode="after")
    def validate_model(self) -> Self:
        """
        Cross-field validation — runs after all field validators.

        Example use case (not implemented here, but shows the pattern):
            if self.status == ProjectStatus.completed and not self.end_date:
                raise ValueError("Completed projects must have an end_date")

        mode="after":
            All fields are already validated and typed correctly.
            self.name is guaranteed to be a str, not None or Any.
        """
        # Add cross-field validation here if needed
        return self


class ProjectUpdate(BaseModel):
    """
    DTO for PATCH /projects/{id} — partial update of an existing project.

    Why all fields are optional:
        PATCH semantics mean "update only the fields I provide".
        If the client sends {"name": "New Name"}, only name is updated.
        owner and status remain unchanged.

        This is different from PUT, which would require all fields
        and replace the entire resource.

    Why this schema exists:
        Same security reason as ProjectCreate — the client must not
        be able to modify id, created_at, or updated_at.

    Validation rules:
        - All fields optional (None means "do not update this field")
        - If provided, same validation as ProjectCreate applies
    """

    name: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="New project name (omit to keep current value)",
    )

    owner: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="New project owner (omit to keep current value)",
    )

    status: ProjectStatus | None = Field(
        default=None,
        description="New project status (omit to keep current value)",
    )

    # ── Validators ────────────────────────────────────────────────────────────

    @field_validator("name", "owner", mode="before")
    @classmethod
    def strip_whitespace(cls, v: str | None) -> str | None:
        """
        Same as ProjectCreate, but handles None (field not provided).

        If v is None: return None (field is not being updated)
        If v is str: strip whitespace and validate
        """
        return v.strip() if v else v

    @field_validator("name")
    @classmethod
    def validate_name_content(cls, v: str | None) -> str | None:
        """Same validation as ProjectCreate, but allows None."""
        if v is None:
            return v
        if "\x00" in v:
            raise ValueError("Project name cannot contain null bytes")
        if "\n" in v or "\r" in v:
            raise ValueError("Project name cannot contain newlines")
        if any(ord(c) < 32 for c in v):
            raise ValueError("Project name cannot contain control characters")
        return v


# ══════════════════════════════════════════════════════════════════════════════
# Response DTOs — what the server sends TO the client
# ══════════════════════════════════════════════════════════════════════════════

class ProjectResponse(BaseModel):
    """
    DTO for single-item responses — GET /projects/{id}, POST /projects, PATCH /projects/{id}.

    Why this schema exists:
        The client needs to see ALL fields including the generated ones:
            - id (so they can reference this project in future requests)
            - created_at (for display and sorting)
            - updated_at (for display and caching)

        This is the full representation of a project.

    model_config from_attributes=True:
        Tells Pydantic to read data from object attributes, not dict keys.

        Without it:
            project_orm = db.query(Project).first()
            ProjectResponse(**project_orm)  # TypeError — Project is not a dict

        With it:
            project_orm = db.query(Project).first()
            ProjectResponse.model_validate(project_orm)  # Works — reads .id, .name, etc.

        This is how you convert an ORM model to a Pydantic schema.
    """

    id: UUID
    name: str
    owner: str
    status: ProjectStatus
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class ProjectSummary(BaseModel):
    """
    DTO for list responses — GET /projects (paginated list).

    Why this schema exists:
        When returning 100 projects, including created_at and updated_at
        for every item adds unnecessary payload size.

        For a list view, the client only needs:
            - id (to link to the detail page)
            - name (to display)
            - owner (to display)
            - status (to display)

        When the user clicks a project to view details, the frontend
        makes a second request to GET /projects/{id} which returns
        the full ProjectResponse with timestamps.

    This is a performance optimization — smaller payloads = faster responses.
    """

    id: UUID
    name: str
    owner: str
    status: ProjectStatus

    model_config = {"from_attributes": True}


# ══════════════════════════════════════════════════════════════════════════════
# Why validation matters — real-world examples
# ══════════════════════════════════════════════════════════════════════════════

"""
Without validation:

    POST /projects
    {
        "name": "",
        "owner": "alice"
    }
    → Creates a project with an empty name. Breaks the UI.

    POST /projects
    {
        "name": "   ",
        "owner": "alice"
    }
    → Creates a project with a whitespace-only name. Breaks search.

    POST /projects
    {
        "name": "Project\x00Name",
        "owner": "alice"
    }
    → Null byte in the name. Breaks C-based log parsers and file systems.

    POST /projects
    {
        "name": "Valid Project",
        "owner": "alice",
        "id": "00000000-0000-0000-0000-000000000001",
        "created_at": "2000-01-01T00:00:00Z"
    }
    → Over-posting attack. Client tries to set database-generated fields.

    PATCH /projects/abc123
    {
        "name": ""
    }
    → Updates the project to have an empty name. Data corruption.


With validation:

    All of the above requests are rejected with HTTP 422 and a clear error message:
        "Validation failed: name: ensure this value has at least 1 characters"
        "Validation failed: name: Project name cannot contain null bytes"
        "Extra inputs are not permitted: id, created_at"

    The database never sees invalid data.
    The service layer never sees invalid data.
    Only the validation layer (Pydantic) sees and rejects it.
"""
